// <auto-generated />
using System;
using Assisment.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assisment.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251020073226_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Assisment.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExperinceYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specializatiion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Coachs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExperinceYears = 5,
                            Name = "Salah",
                            Specializatiion = "Basketball"
                        },
                        new
                        {
                            Id = 2,
                            ExperinceYears = 8,
                            Name = "Mohamed",
                            Specializatiion = "Football"
                        },
                        new
                        {
                            Id = 3,
                            ExperinceYears = 2,
                            Name = "Ahmed",
                            Specializatiion = "Volyball"
                        },
                        new
                        {
                            Id = 4,
                            ExperinceYears = 1,
                            Name = "Nour",
                            Specializatiion = "Tenis"
                        },
                        new
                        {
                            Id = 5,
                            ExperinceYears = 6,
                            Name = "Omar",
                            Specializatiion = "Golf"
                        });
                });

            modelBuilder.Entity("Assisment.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Competitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2003),
                            Location = "Nasr Club",
                            Title = "ComboB"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2000),
                            Location = "Mansoura",
                            Title = "Pollan"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2013),
                            Location = "Street",
                            Title = "Fatns"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2013),
                            Location = "Pyramids",
                            Title = "Eating the ground"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1995),
                            Location = "My home",
                            Title = "Fangle"
                        });
                });

            modelBuilder.Entity("Assisment.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 10,
                            FullName = "Fawzy",
                            Position = "Attack",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 16,
                            FullName = "Gamal",
                            Position = "Defense",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 18,
                            FullName = "Ans",
                            Position = "L Wing",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 4,
                            Age = 16,
                            FullName = "Yassin",
                            Position = "R Wing",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 5,
                            Age = 19,
                            FullName = "Ibrahem",
                            Position = "Goal keper",
                            TeamId = 5
                        });
                });

            modelBuilder.Entity("Assisment.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Giza",
                            CoachId = 1,
                            Name = "Trackers"
                        },
                        new
                        {
                            Id = 2,
                            City = "Cairo",
                            CoachId = 2,
                            Name = "Good"
                        },
                        new
                        {
                            Id = 3,
                            City = "Haram",
                            CoachId = 3,
                            Name = "Bad"
                        },
                        new
                        {
                            Id = 4,
                            City = "Nasr",
                            CoachId = 4,
                            Name = "Nice"
                        },
                        new
                        {
                            Id = 5,
                            City = "Tahrir",
                            CoachId = 5,
                            Name = "Smachers"
                        });
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.Property<int>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("CompetitionId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("CompetitionTeam");
                });

            modelBuilder.Entity("Assisment.Models.Player", b =>
                {
                    b.HasOne("Assisment.Models.Team", "Team")
                        .WithMany("Player")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Assisment.Models.Team", b =>
                {
                    b.HasOne("Assisment.Models.Coach", "Coach")
                        .WithOne("Team")
                        .HasForeignKey("Assisment.Models.Team", "CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("CompetitionTeam", b =>
                {
                    b.HasOne("Assisment.Models.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Assisment.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Assisment.Models.Coach", b =>
                {
                    b.Navigation("Team")
                        .IsRequired();
                });

            modelBuilder.Entity("Assisment.Models.Team", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
